#!/bin/sh
# $Id: pidstatd,v 1.4 2003/11/14 21:25:43 wsnyder Exp $
# DESCRIPTION: Sample file to place in /etc/init.d to start the daemon
# Distributed with IPC::Locker
#
# Copyright 1999-2003 by Wilson Snyder.  This program is free software;
# you can redistribute it and/or modify it under the terms of either the GNU
# General Public License or the Perl Artistic License.

state=$1

# Source site start file
if [ -x /usr/local/common/etc/profile.d/site.sh ] ; then
    . /usr/local/common/etc/profile.d/site.sh
fi

case $state in
  start)
        echo starting /usr/local/bin/pidstatd if present
	if [ $EUID != 0 ]; then
	    echo "Run as root, only root can do kill 0's"  
	    exit 10
	fi
        [ -f /usr/local/bin/pidstatd ] && /usr/local/bin/pidstatd &
        ;;
  stop)
        if test "x`pidof -o $$ -o $PPID -x pidstatd`" != x; then
                echo -n $"Stopping pidstatd: "
                kill `pidof -o $$ -o $PPID -x pidstatd`
                echo
        fi
	exit 0
        ;;
  restart|reload)
	$0 stop
	$0 start
	exit 0
	;;
  status)
        if test "x`pidof -o $$ -o $PPID -x pidstatd`" != x; then
  	        ps f -ww `pidof -o $$ -o $PPID -x pidstatd`
        fi
	exit 0
	;;
*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
